= Cypress testing

The project uses Cypress to virtualize actions (button clicks, key inputs, ...) the web interface and test certain features.

== Adding cypress and configuration

Installing cypress is one of the easy tasks:

Depending on your package manager just add the cypress module in your project.

With _npm_:

[source,cli]
----
npm install cypress --save-dev
----

With _yarn_:

[source,cli]
----
yarn add cypress --dev
----

The first thing you have to do is to open cypress. To do that you have to run the following command:

Using npx from npm (npm > v5.2):

[source,cli]
----
npx cypress open
----

With _yarn_:

[source,cli]
----
yarn run cypress open
----

== Testing Types

There are two different types of testing with cypress:

* End-to-End Testing (E2E)
* Component Testing

both can be used to test certain aspects of the project.

> In the end, you will probably have a combination of both types of tests for your app, but how do you choose right now?

Source: https://docs.cypress.io/guides/core-concepts/testing-types


=== E2E Testing

Ent-to-End Testing is the _new_ type what made cypress special that it has been chosen by the team. It is working with a virtual browser which is testing your webapp like a real user (clicking URLs, links and buttons).

This type tests the whole functionality inclusive HTTP Requests, asynchronous methods/imports and or other certain integration-features.

> * Benefits of end-to-end tests:
** Ensure your app is functioning as a cohesive whole
** Tests match the user experience
** Can be written by developers or QA Teams
** Can be used for integration testing as well

> * Considerations for end-to-end tests:
** More difficult to set up, run, and maintain
** Provision testing infrastructure in CI
** Testing certain scenarios require more setup

> * Common scenarios for end-to-end tests:
** Validating critical workflows like authentication and purchasing
** Ensuring data is persisted and displayed through multiple screens
** Running Smoke Tests and System Checks before deployment

Source (All the 3 above): https://docs.cypress.io/guides/core-concepts/testing-types

=== Component Testing

On the other hand cypress have the component testing. Components are parts of the website ranging from small input fields and text to large panels containing different other nested components.

Every component can be _mounted_ and tested. That means while testing only the component will be rendered and loaded. (Not the whole application as in E2E)

Component Tests are comparable to unit tests. They are made for a specific part of a program in that case a component. The difference to E2E is that integration features are not checked and the program could still not work even the tests are succeeding.


> * Benefits of component tests:
** Easier to test components in isolation
** Fast and reliable
** Easy to set up specific scenarios in tests
** Don't rely on any external system to run

> * Considerations for component tests:
** Do not ensure overall app quality
** Do not call into external APIs/Services
** Usually written by developers working on the component

> * Common scenarios for component tests:
** Testing a date picker works properly for a variety of scenarios
** That a form shows and hides specific sections based on input
** Testing components coming out of a design system
** Testing logic not tied to a component (like unit tests!)

Source (All the 3 above): https://docs.cypress.io/guides/core-concepts/testing-types

== Cucumber API
image::../../../Assets/Images/Fabian_Maurutschek/cucumber-open-icon.svg[]
Cucumber is a modern Behavior-Driven Development tool used in the 3D printing web interface for testing purposes.

Features of cucumber:

> * Cross platform:
* Automation
* Plain Text
* Shared Understanding
* Automate
* Reports
* Integrations

The biggest advantage of cucumber is the easy-to-understand text cases together with cypress:

[source, cucumber]
----
Feature: Press Light Button
    Scenario: opening App and press light btn
        When I visit "localhost/hc"
		Then I click onto the Lightbutton
----

These Features are going to be preprocessed by cypress:

[source, typescript]
----
const { When, Then, Given } = require("@badeball/cypress-cucumber-preprocessor");

When("I visit {string}", (url) => {
	cy.visit("http://" + url);
});

Then("I click onto the Lightbutton", () => {
	cy.get('[data-testid="light-button"]').click()
});
----
