
== 1.6 Visual Design

An applications visual appeal can be split up into several parts. The most important ones are:

- Typography

Using different fonts and sizes to emphasize different parts of the text 
Typography is the art to emphasize on text. Highlighting, quoting and maintaining text readability are the challenges typography faces.

- Colors

Highlighting elements & reflect the applications purpose
Making several peaces blend together to create one harmonious whole and creating a visual hierarchy 

- Layout

The Page Layout is the implicit object arrangement and positioning of elements. The visual representation of the information must be ordered and spaced in a way that it is easy to read and understand. Creating a flow of information is the key to create an outstanding web layout for any project.

- Motion

Action - Reaction

=== 1.6.1 Languages

The languages used to implement visual tweaks are:

- HTML
- XHTML
- XML
- CSS
- SCSS

<<<

==== 1.6.1.1 HTML

HTML also known as Hypertext Markup language is the World wide web's standard markup language. HTML was developed by the World Wide Web Consortium **(W3C)** in 1989 to semantically describe scientific documents for exchange on the internet. But its purpose has changed since the start. HTMLs general design enabled it to be adapted over the years. It is now the most common language for describing a web page's structure and serves as the foundation for the modern web.
The newest version HTML 5.2 has been released in 2017 by **W3C** and **WHATWG** which continuously work on updating the language.

[source,html,title="HTML example ^[1]^"]
----
<!DOCTYPE html>
<html>
<body>

<h2 title="I'm a header">The title Attribute</h2>

<p title="I'm a tooltip">Mouse over this paragraph, to display the title attribute as a tooltip.</p>

</body>
</html>
----

<<<
    
==== 1.6.1.2 CSS / SCSS

**CSS**
Cascading Style Sheets are used to describe the look of Web pages including coloring of elements, fonts and alignment. The presentation of a document can be controlled for every size and format by CSS. This results in configurable varying layouts for different devices.

[source,css,title="CSS example ^[2]^"]
----
body {
  background-color: #ffffff;
  font-family: Lato;
  font-size: 16px;
  color: #333333;
}

----


**SCSS**
SCSS is a CSS preprocessor. It is a scripting language that is compiled into CSS. SCSS has been developed to extend the CSS language, adding nested rules, variables, mixins, selector inheritance, and more. organizing and maintaining stylesheets is way faster and easier than its predecessor CSS, as it completely removes the repetitiveness of CSS code.


[source,scss,title="SCSS example 1 ^[3]^"]
----
$font-stack: Arial, sans-serif;     
$primary-color: #333333;

//Variable definition

body {
  background-color: #ffffff;
  font-family: $font-stack;
  font-size: 16px;
  color: $primary-color;
}
----

<<<
  
Additionally SCSS is able to interpret multiple line comments and nested design configurations, which are not supported by the base css language.
Therefore, an example for a **nav ul** class would the following:

[source,scss,title="SCSS example 2^[4]^]
----
nav {
  background-color:#333;
  padding:1em;
  ul {
    margin:0;
    padding:0;
  }
}
----

Modern web pages try to avoid spending time on custom css classes but rather use a framework that has prebuilt classes or components. These frameworks and libraries are described in one of the following chapters.


<<<

=== 1.6.2 Typography
Psychological definition of colors and how to emphasize that in your code

There are several ways to implement typography in projects. 
With the most common being:

- local definition 

1. defining the font type directly in elements with the "font-family" property.
2. defining it in a local css space.

These implementations are not recommended as they are not scalable and can lead to a lot of code duplication.
It is recommended to use these techniques only when using a font that sticks to **one** component.
As this is a very specific edge case, it only applies to a few cases where it is more important to keep the font semantically separate from the rest of the application.


- global definition

*Defining the font in a global css file, provides a more scalable solution. It reduces code duplication and makes it easier to change the font in the future. Making it the best solution for projects with one or two universally used fonts.*

[source,css,title="Typography example ^[5]^"]
====
html {
    font-family: 'Lato', serif;
    font-size: 1.5vmin;
}
==== 

The actual consideration of the fonts is its own expertise. But there are some general rules that are applicable most of the time, and should be considered when choosing a font for an element.

Firstly, applications that try to provide an easy usability should consider to include as little text as possible. Intuition cannot be created through fonts and text. 

While phrases written in Capital letters can be utilized to highlight important information, it is way harder to read than a combination of upper and lower case letters. As an example, the phrase **"HELLO WORLD"** can be also written in the more readable form of **"Hello world"**. 

Additionally, the text-color should be chosen to be in contrast with its background. The general rule of thumb is to chose an 80% contrasting color, to avoid the text from being too hard to read.

Readability can also be improved by choosing a text size and its typeface that appears to by really crisp on screen.  For that purpose, 
Alan Cooper,
Robert Reimann and
David Cronin recommend to use a font size of 10px or higher as well as a font family that is equally readable as Tahoma or Verdana.


<<<
