# Visual Design

- More technical Approach (Dos and dont's for visual design)
What code is considered clear for specific topics

An applications visual appeal can be split up into several parts. The most important ones are:
- Typography
> Using different Fonts and sizes to emphasize different parts of the text 
- Colors
> Highlighting Elements & reflect the applications purpose
- Layout
> Object arrangement
- Motion
> Action - Reaction

## Typography
Psychological definition of colours and how to emphasize that in your code

There are several ways to implement typography in projects. 
With the most common being:

- local definition 

1. defining the font type directly in elements with the "font-family" property.
2. defining it in a local css space.

These implementations are not recommended as they are not scalable and can lead to a lot of code duplication.
It is recommended to use these techniques only when using a font that sticks to **one** component.
As this is a very specific edge case, it only applies to a few cases where it is more important to keep the font semantically seperate from the rest of the application.


- global definition

*Defining the font in a global css file, provides a more scalable solution. It reduces code duplication and makes it easier to change the font in the future. Making it the best solution for projects with one or two universally used fonts.*

[source,css]
====
html {
    font-family: 'Lato', serif;
    font-size: 1.5vmin;
}
====

## Colors equal decisions
Psychological definition of colours and how to emphasize that in your code - Psychological aspect + Code recommendation

## Page Layout
How to you code layout in a way that is clear and easy to understand - Code readability

## Motion
How should software act and react to user input