= 2.7 Implementation of the 3D Viewer 

The Lithoz 3D Printing Web Interface has an integrated 3D viewer that is build with the three.js. In this section explains the decisions and implementation behind it.  

== 2.7.2 Why Three.js

Form to the other WebGL frameworks we discussed earlier game engines, such as Babylon.js, A-frame, PlayCanvas and Unity can be ruled out, because they include features that are not needed. Verge3D also includes a lot of features that are unnecessary for the 3D viewer, like the Blender and Maya integration. Another requirement is the support of stl files, because the 3D objects are transmitted in stl files from the backend. A-Frame for example does not support stl files and can not be used for the 3D viewer because of it.

== 2.7.3 Implementation

Now lets take a look at the implementation:

[source, HTML]
----
<template>
<div id="3dViewer" style="height: 42vh; width: 60vw">

</div>
</template>
<script setup lang="ts">
import * as THREE from 'three';
import {Mesh, Vector3} from 'three';
import {STLLoader} from "three/examples/jsm/loaders/STLLoader";
import {onMounted, ref} from "vue";
import {OrbitControls} from "three/examples/jsm/controls/OrbitControls";
import {getCurrentSTLPath} from "@/store/DataStates";
import {applicationConnected, generalState, webState} from "@/store/GeneralStates";
import {preparedRunState} from "@/store/DataStates";

var layerMesh: Mesh
var box: THREE.Box3

let container: HTMLElement | null,
	camera: THREE.PerspectiveCamera,
	cameraTarget: THREE.Vector3,
	scene: THREE.Scene,
	renderer: THREE.WebGLRenderer,
	controls: OrbitControls;

onMounted(() => {
	webState.value.loadingImage = true;
	console.debug("Loading 3D Viewer")
	init();
	animate();
	onWindowResize();
	console.debug("Finished loading 3D Viewer")
})

function init() {
	container = document.getElementById( '3dViewer' );

	camera = new THREE.PerspectiveCamera( 35, window.innerWidth / window.innerHeight, .1, 2000 );
	camera.position.set( 30, 0, 0 );

	cameraTarget = new Vector3(0,0,0)

	scene = new THREE.Scene();
	scene.background = new THREE.Color( "#444444" );

	const loader = new STLLoader();
	const material = new THREE.MeshPhongMaterial( { color: "#AAAAAA", specular: "#111111", shininess: 200 } );

	// Colored binary STL
	loader.load(getCurrentSTLPath(), function ( geometry ) {

		let meshMaterial = material;


		const mesh = new THREE.Mesh(geometry, meshMaterial);

		box = new THREE.Box3().setFromObject( mesh );
		cameraTarget = new Vector3(box.max.x - box.min.x, box.max.y - box.min.y, box.max.z - box.min.z)

		console.log( cameraTarget);

		mesh.position.set(0, 0, 0);
		mesh.rotation.set(  Math.PI / 2, Math.PI, Math.PI / 2 );
		mesh.scale.set( 0.5, 0.5, 0.5 );

		mesh.castShadow = true;
		mesh.receiveShadow = true;

		//layer mesh
		const layerGeometry = new THREE.BoxGeometry( box.max.y - box.min.y, 0, box.max.x - box.min.x)
		const layerMaterial = new THREE.MeshBasicMaterial( { color: 0xffff00, opacity: 0.3, transparent: true } );
		layerMesh = new THREE.Mesh( layerGeometry, layerMaterial );

		layerMesh.position.set((box.max.y - box.min.y) / 2, ((box.max.z - box.min.z) * (webState.value.layerImageLayer / preparedRunState.value.total_layers)) * 0.5, (box.max.x - box.min.x) / 2)
		//layerMesh.rotation.set( 0, Math.PI, 0 );
		layerMesh.scale.set( 0.5, 0.5, 0.5 );

		scene.add(layerMesh);

		scene.add( mesh );
		webState.value.loadingImage = false;
	} );

	

	// Lights
	scene.add( new THREE.HemisphereLight( 0x443333, 0x111122 ) );

	addShadowedLight( 1, 1, 1, "#ffffff", 1 );
	addShadowedLight( 0.5, 1, - 1, "#ffffff", 1 );
	// renderer

	renderer = new THREE.WebGLRenderer( {
		antialias: false,
		stencil: false
	});
	renderer.setPixelRatio( window.devicePixelRatio );
	renderer.setSize(container?.clientWidth ?? 0, container?.clientHeight ?? 0);
	renderer.outputEncoding = THREE.sRGBEncoding;

	renderer.shadowMap.enabled = true;

	//controls
	controls = new OrbitControls( camera, renderer.domElement );

	container?.appendChild( renderer.domElement );
	window.addEventListener( 'resize', onWindowResize );
}

function addShadowedLight( x: number, y: number, z: number, color: THREE.ColorRepresentation | undefined, intensity: number | undefined ) {

	const directionalLight = new THREE.DirectionalLight( color, intensity );
	directionalLight.position.set( x, y, z );
	scene.add( directionalLight );

	directionalLight.castShadow = true;

	const d = 1;
	directionalLight.shadow.camera.left = - d;
	directionalLight.shadow.camera.right = d;
	directionalLight.shadow.camera.top = d;
	directionalLight.shadow.camera.bottom = - d;
	directionalLight.shadow.camera.near = 1;
	directionalLight.shadow.camera.far = 4;
	directionalLight.shadow.bias = - 0.002;

}

function onWindowResize() {
	camera.aspect = window.innerWidth / window.innerHeight;
	camera.updateProjectionMatrix();
	renderer.setSize( container?.clientWidth ?? 0, container?.clientHeight ?? 0);
}

function animate() {
	requestAnimationFrame( animate );
	if(layerMesh && box){
		layerMesh.position.set((box.max.y - box.min.y) / 4, ((box.max.z - box.min.z) * (webState.value.layerImageLayer / preparedRunState.value.total_layers)) * 0.5, (box.max.x - box.min.x) / 4)
	}
	render();
}

function render() {
	camera.lookAt(cameraTarget);
	controls.update();
	renderer.render( scene, camera );
}

</script>
----

When the 3D viewer is loaded into the HTML page the onMount() function is called this function then calls three functions. Those three functions are the init() function that initializes the scene and loads the stl file, the animate() function starts the animation loop and the onWindowResize() method handles the size of the canvas when the window size changes.

=== 2.7.4 init()

The init() method first initializes the camera, scene and renderer like we discussed in the last chapter. Then it needs to load the stl file, which it does by using an STLloader and calling the load() method. The load() method takes the return value from the getCurrentStlPath() method, which fetches the stl data from the backend, as an attribute. The returned data from the stl file is then passed into a new mesh and the mesh is rotated, because the data received from the backend is rotated in the wrong direction.

Then there is another 3D object instantiated, the layer plane, which indicates at which layer the printing process currently is. The plane is then, together with the object loaded from the stl, added to the scene.

After that there are two lights added to the scene and an orbit controller instantiated, that is used by the user of the 3D Printing Web Interface to rotate the camera around and zoom in and out. There is also a event listener added that is called when the window size changes and calls the onWIndowResize() method.

=== 2.7.5 animate()

The animate() method is the animations loop and sets the layer plane at the correct position, according to the layer slider, which can be used by the users to select a specific layer. It then calls the render function, which updates the the orbit controller, rotates the camera to look at the 3D object and renders the scene.

=== 2.7.6 onWindowResize()

This function resizes the aspect ratio of the camera back to the right size when the size of the window changes, updates the projection matrix, which is required to apply the changes and resizes the renderer.