= 4.3 Alternatives to MQTT

== 4.3.1 RabbitMQ
It is one the most deployed open source message broker around the world. RabbitMQ has a similar purpose as the MQTT protocol.

=== 4.3.1.1 Features

==== Asynchronous Messaging 
Supports multiple messaging protocols, delivery acknowledgement, message queuing, flexible routing to queues, multiple exchange type.

==== Developer Experience 
Deployable with Kubernetes, BOSH, Chef, Docker and Puppet.

==== Enterprise and Cloud Ready
Easy deployable in public and private clouds. Supports TLS and LDAP.

==== Monitoring
RabbitMQ provides an UI for managing and monitoring RabbitMQ.

==== Flexible Routing 
Before reaching queues, messages are routed through exchanges. Many built-in exchange kinds are available in RabbitMQ for conventional routing logic. You can connect exchanges together for more complicated routing, or even create your own exchange type as a plugin.

==== Reliability 
Persistence, delivery acknowledgements, publisher confirms, and high availability are just a few of the capabilities that RabbitMQ provides to allow you trade off performance with reliability.

<<<

== 4.3.2 XMPP
Extensible Messaging and Presence Protocol (XMPP) is a collection of open standards for instant messaging, presence, group chat, phone and video conversations, collaboration, lightweight middleware, content syndication, and generalized routing of XML data.

In order to provide an open, decentralized alternative to the closed instant messaging services available at the time, XMPP was initially created in the Jabber open-source community. Over these services, XMPP has a number of significant advantages.

=== 4.3.2 Features

==== Open
The XMPP protocols are free to use and easy understandable.

==== Proven 
Jeremie Miller created the first Jabber/XMPP technologies in 1998. Hundreds of developers are currently working on these technologies, and millions of people use XMPP for instant messaging through open platforms like Google Talk.

==== Decentralized
The XMPP network is similar to the email architecture; anyone can host their own XMPP server, enabling individuals and organizations to take control of their communications experience.

==== Secure 
There main security standards are SASL and TSL such as in MQTT. To further increase security, the XMPP developer community is currently working on end-to-end encryption.

==== Extensible 
Anybody can add additional functionality on top of the core protocols by utilizing the power of XML. Common extensions are published in the XEP series to ensure interoperability, but this publication is optional and organizations are free to retain their own private extensions.

==== Flexibility 
Beyond instant messaging, XMPP applications include cloud computing, network management, content syndication, collaboration tools, file sharing, gaming, remote system monitoring, and many more.

==== Widely used 
You can create and distribute real-time apps and services from a variety of businesses and open-source initiatives. You won't ever be "locked in" while using the XMPP technology.

<<<

== 4.3.3 Kafka
Several businesses use Apache Kafka it is an open-source distributed event streaming platform, for mission-critical applications, high-performance data pipelines, streaming analytics, and data integration.

=== 4.3.3.1 Core capabilities

==== High throughput
Send messages using a cluster of devices with latencies as low as 2ms at network-limited throughput.

==== Scalability 
Up to 1,000 brokers, billions of messages a day, petabytes of data, and hundreds of thousands of partitions can be handled by large production clusters. Storage and processing should be dynamic in size.

==== Permanent storage
Safely store data streams in a fault-tolerant, distributed, and long-lasting cluster.

==== High availability
Clusters can be efficiently extended over availability zones or linked together across geographical regions.

=== Ecosystem

==== Built-in stream processing
Using event-time and exactly-once processing, handle streams of events with joins, aggregations, filters, transformations, and more.

==== Connection
The Kafka Connect interface's out-of-the-box integrations with hundreds of event sinks and sources, including Postgres, JMS, Elasticsearch, AWS S3, and others.

==== Client libraries
Streams of events can be read, written, and processed in a wide variety of computer languages.

==== Open Source Tools
There is a large amount of open source tools available.