= Correct and Clean Testing


== Test Driven Development / Test Driven Design (TDD)

Test driven development is trying to achieve clean and reliable code. The main difference is that the code is based on tests. Usually developers are writing the code first and afterwards testing it with unit/integration tests.

1. In TDD the test hast to be written first. Keep in mind what goal is going to be achieved when the testcase is completed. It has to be set correctly and must fail at start.

2. Afterwards the code is going to be simple and short programmed. The simpler the code is the better the output (Do not exaggerate it has to be short and modular). If all tests of that code are succeeding you can proceed to the next step.

3. Refactor the code with different and new tests. Ensure that the test cases are passing and the functionality is the same or better.


> * Examples of refactoring:
* moving code to where it most logically belongs
* removing duplicate code
* making names self-documenting
* splitting methods into smaller pieces
* re-arranging inheritance hierarchies

Source: https://en.wikipedia.org/wiki/Test-driven_development

Keep in mind that test driven development is not the standard and best style to develop on projects. It could be not perfect for every group/team also it is more common used in agile development.

== Behaviour Driven Development

BDD is a development style that is designed to make the communication between stakeholders, team-members and other developers easier and more simple.

Focuses of Behaviour Driven Development:

> * Where to start in the process
* What to test and what not to test
* How much to test in one go
* What to call the tests
* How to understand why a test fails

Source: https://en.wikipedia.org/wiki/Behavior-driven_development

=== Issue and Description Structure

Behaviour Driven Development has certain _keywords_ that are used in user stories, descriptions, bug issues and comments.

Keywords of Issues:

[source, text]
----
As a <name> (...)
I want (...)
so that (...)
----

Example:

`*As a* buyer *I want* to select and split revenue during checkout *so that* multiple NGOs will be supported.`

Keywords of Scenarios:

> * *Given*: the initial context at the beginning of the scenario, in one or more clauses;
* *When*: the event that triggers the scenario;
* *Then*: the expected outcome, in one or more clauses.

Source: https://en.wikipedia.org/wiki/Behavior-driven_development

=== Ubiquitous Language



