= Correct and Clean Testing


== Test Driven Development / Test Driven Design (TDD)

Test driven development is trying to achive clean and reliable code. The main difference is that the code is based on tests. Usually developers are writing the code first and afterwards testing it with unit/integration tests.

1. In TDD the test hast to be written first. Keep in mind what goal is going to be achived when the testcase is completed. It has to be set correctly and must fail at start.

2. Afterwards the code is going to be simple and short programmed. The simpler the code is the better the output (Do not exaggerate it has to be short and modular). If all tests of that code are succeding you can proceed to the next step.

3. Refactor the code with different and new tests. Ensure that the test cases are passing and the functionality is the same or better.


> * Examples of refractoring:
* moving code to where it most logically belongs
* removing duplicate code
* making names self-documenting
* splitting methods into smaller pieces
* re-arranging inheritance hierarchies

Source: https://en.wikipedia.org/wiki/Test-driven_development

Keep in mind that test driven development is not the standard and best style to develop on projects. It could be not perfect for every group/team also it is more common used in agile development.

== Behaviour Driven Development

