== Mocking

Mocking is the process of creating a design prototype of an application. It is used to explore the design of the application without the implementation effort . Mocking is a very important step in the design process, since it allows to create many different design ideas in a short period of time.
This way, the apps visual structure can be improved before creating the production ready product.

[quote,Nick Babich,Adobe XD - Web design guidelines[4]]
"Mockups are high-fidelity design artifacts that enable designers to see what the final layout will look like."

Manifesting design ideas can provide clarity about the desired appeal.
There are several tools to choose from, when creating a mockup. 

The most popular ones are Adobe XD, Figma and Sketch.

[%header,cols="1,6,5,4"]
|===
| **Nr** 
| **Name** 
| **Feature**
| **Collaboration Features**

| 1 
| Adobe XD 
| Paid 
| Yes

| 2 
| Figma 
| (3 Free projects)  
| Yes

| 3 
| Sketch
| Free 
| Yes
|=== 

Figma in particular includes Wireframing, Prototyping, and Mocking in one combined online application.
Its powerful environment allows for easy mockup creations for several industries. The fact that it is free, makes it the most attractive option for most developers.
With the great collaboration features and a series of ad-ons, it is an intuitive choice to create mocks in teams. 


