= Quality assurance techniques

== Writing clean code

> How do I become a good programmer?

Many aspects and much practise have to be done to write good and clean code. From naming conventions to domain design everything is important to become a good software engineer. Nobody is and can be perfect. Also, there is always a way to improve.

To improve the quality of code there are some simple aspects:

=== 1. Naming Conventions

Certain programming languages have different ruiles of the naming conventions. But it is

*Naming Conventions in JAVA*

- Fields are small and in camel case with small leading letter

[source,java]
----
private int myInt;
public int myInt;
----


- Classes are in camel case with big leading letter
[source,java]
----
public class MyInterestingClass{
	...
};
----

- Constants are capitalized
[source,java]
----
public final String PROGRAM_VERSION_ID = "0.1.0.DEV_BUILD.1"
----

*Naming Conventions in C#*

- Private attributes are leading with an underscore
[source,Csharp]
----
private int _myInt;
----

- Properties and classes are in camel case with big leading letter
[source,Csharp]
----
public class MyInterestingClass{
	public int MyProp {get; set;} = 0;
};
----

- Constants are capitalized
[source,Csharp]
----
public final String PROGRAM_VERSION_ID = "0.1.0.DEV_BUILD.1"
----

=== 2. Variable Scope

The first way to make code better readable is to name the variables legible. Avoid using simple letters or words for import variables.

[source, java]
----
public class MyInterestingClass{
	private int a;
	private int thisVariableIsUsedForThat;
}
----

Learning to name variables properly is not an easy thing, because other team-members have 0 relation to the own code.

=== 3. Comments

Additionally, to the Variable Scope comments are also a good aspect for better understanding and reading by team-members. Usually the content of comments are different:

- Comments that explain *WHAT* the code is doing.

- Comments that explain *HOW* the code is working.

Example

[source,java]
----
public int calc(int number1, int number2){
	return number1 % number2;
}
----

Comment that explains *WHAT* the code is doing:

`This method takes the modulo of number1 and number2.`

Comments that explain *HOW* the code is working:

`This method devides number1 and number2 and subtracts number1 with the result of the devision.`

_Most developer know what the modulo operator does. Do not comment such things extra!_

=== 4. Modularity

Theoretically every program can be written in one line in one class. But having all the code in one _chunk_ with big projects and version management that will make life hard.

The same goes for methods and classes:

- Keep methods small, easy to understand and modular (more usable)

That will help testing the method, and it could be better extendable and refactorable afterwards.

=== 5. Exception & Error handling

Do not see exceptions as bad invention! Proper use of errors and exceptions have a fantastic advantage if it is used wisely.

- Keep the messages understandable
- Use the correct type of exception (NullReferenceE./NullPointerE., InvalidArgumentE.,...)


== Programming style

There are two different types of code: Declarative (Functional) and Imperative Code. The code brings at the end the same result but the implementation is different. It depends on the project which programming style is better for development. But we can extract certain aspects in the later sections. The main difference is not easy to explain:

> Declarative Programming is: *What* the program has to do.

> Imperative Programming is: *How* the program should do it.

In high level programming languages such as JAVA, C#, ... it is preferred to use the declarative Programming, while in more hardware-near programming imperative is more common.

=== Imperative programming

Making projects imperative is easier than declarative. The first code will be very simple and easy using basic _if_ and _for_ which is common for imperative programming.

=== Declarative programming

The most know declarative language is SQL it is also the best example.:

[source, sql]
----
SELECT *
FROM myTable
WHERE id = 34
----

Everybody (Who knows SQL) is able to read that statement. Also, it is easy to understand and tells exactly what to do.

It commands directly what the process has to do and not how to do it (for example with for loops)

=== Examples

To better understand the difference of imperative and declarative programming there is an example provided in JAVA:

These examples provide the same return value.

*Imperative*
[source,java]
----

List<Integer> arr = List.of(1,2,3,4,5,6,7,8,9,10,11,12,13);

for(int i = 0; i < arr.length; i++)
	if(arr[i] == 3)
		return arr[i];
----

*Declarative*
[source,java]
----

List<Integer> arr = List.of(1,2,3,4,5,6,7,8,9,10,11,12,13);

return arr.stream().filter(integer -> integer.intValue() == 3).findAny().get();
----

As you can see the stream api helps a lot to make use of functional programming.
