== 1.7 UI Component Libraries & UI Frameworks

In the world of web design, there are many ways to utilize on existing Design Systems. One of which are UI Component Libraries and Frameworks. These are pre-built components that can be used to build out your website. They are usually built with a specific framework in mind, but can be mostly used in any framework of your choice.

=== 1.7.1 Bootstrap
Bootstrap is the most well known and used UI library in the world.

==== 1.7.1.1 Installation
There are two separate ways to use Bootstrap in your project. 

. Installing the newest version of Bootstrap - **5.3.0-alpha1**
[source, terminal]
----
> npm install bootstrap@5.3.0-alpha1
----

[start=2]
. Include via links in your HTML file
*Bootstrap requires the usage of an HTML5 doctype, for complete usage of their features.*

[source, html]
----
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
----

You can also download the Bootstrap CSS file and include it into the project. This allows for individual changes in the Bootstrap config.

==== 1.7.1.2 Usage 

Bootstrap is all about preconfigured CSS classes. These can be used to style your HTML elements, regardless of the framework you are using. 

<<<

=== 1.7.2 Vuetify

Vuetify is an UI library designed to be used in Vue.js projects. Since it is a newer library, it is not as well known than bootstrap , material UI or tailwind CSS. However, it is a very powerful library that can be used to create beautiful and responsive websites. It is also very easy to use and has a lot of prebuilt components. The bad side about its newest version "vuetify 3", is its lack of documentation. Not all functions and components are fully documented, and some of them are even unfinished. However, the company behind vuetify is very active and is constantly working on improving the library.
 
The library can be installed via npm or yarn. It is a package that needs to be added through one of the following commands.

[source, terminal]
----
> yarn add vuetify@^3.1.11
----

[source, terminal]
----
> npm install vuetify@^3.1.11
----

Vuetify is used such as implementing normal HTML elements, mostly starting with "v-" such as "v-btn" or "v-card". It is also used to implement components such as "v-app-bar" or "v-navigation-drawer".
An example for such a component can be found in the project "Lithoz 3D printing web interface" as quoted below.


[source, html]
----
<template>
    <v-col col="5"
		   :style="`cursor: ${cursorRef}`"
           style="display: flex;justify-content: center;align-items: center;">
        <v-btn :disabled="!buttonGenerallyEnabled || disabled"
               width="100%"
			   @click="isBtnState1 ? sendCommand(primaryCommand) : sendCommand(secondaryCommand)"
               :height="height ?? '17vh'"
               style="white-space: normal;"

               flat>
            <b class="wrapWord" style="width:10vw;text-align:center;overflow-wrap: break-word;" >
				{{
		            buttonText !== undefined ? buttonText :
			            $t(isBtnState1 ? textAssets[primaryCommand] : textAssets[secondaryCommand])
				}}
			</b>
        </v-btn>
    </v-col>
</template>
----

=== 1.7.3 Tailwind CSS
Tailwind is an open source css framework, that is used to create designs faster. In contrast to other frameworks, it does not provide any prebuilt components. Instead, it provides a set of utility classes that can be used to mix and match for the styling of HTML elements. This allows for a lot of flexibility and customization. This concept is called *"utility-first"*.

[source,terminal]
----
> npm install -D tailwindcss
> npx tailwindcss init
----

Adding your own template files can be achieved by adding the paths of those files into the tailwind.config.js file.

[source,js]
----
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  plugins: [],
}
----

After configuring and installing tailwind, it has to be imported into your main html file.

[source,html]
----
@tailwind base;
@tailwind components;
@tailwind utilities;
----

An example of tailwinds flexible classes, is the following code snippet. It creates a flexbox with three elements. The first element has a fixed width of 14rem, while the other two elements have a flexible width. The "flex-initial" class indicates that the element is able to shrink dependent on the available space in the flexbox, but is not able to grow.

[source,html]
----
<div class="flex">
  <div class="flex-none w-14 h-14">
    01
  </div>
  <div class="flex-initial w-64 ...">
    02
  </div>
  <div class="flex-initial w-32 ...">
    03
  </div>
</div>
----

=== 1.7.4 MUI - Material UI

Material UI is a UI library made for the React framework. It is a very popular library, that is used by many companies. It is also very well documented and has a lot of prebuilt components. MUI is based on the material design guidelines, which are a set of guidelines for the design of websites and applications. The library can be installed via npm or yarn. It is a package that needs to be added through one of the following commands.

[source, terminal]
----
npm install @mui/material @emotion/react @emotion/styled
----

[source, terminal]
----
yarn add @mui/material @emotion/react @emotion/styled
----

These commands just include the default library. There are also versions online that automatically include styled components, icons and other libraries. These can be found on the official website of MUI.

MUIs usage is very similar to bootstrap. It is based on preconfigured CSS classes. These can be used to style your HTML elements, regardless of the framework you are using. An official example of such a component can be found quoted below.

[source, js]
----
import * as React from 'react';
import Button from '@mui/material/Button';

export default function MyApp() {
  return (
    <div>
      <Button variant="contained">Hello World</Button>
    </div>
  );
}
----