== UI Component Libraries & UI Frameworks

In the world of web design, there are many ways to utilize on existing Design Systems. One of which are UI Component Libraries and Frameworks. These are pre-built components that can be used to build out your website. They are usually built with a specific framework in mind, but can be mostly used in any framework of your choice.

=== Bootstrap
Bootstrap is the most well known and used UI library in the world.

==== Installation
There are two separate ways to use Bootstrap in your project. 

1. Installing the newest version of Bootstrap - **5.3.0-alpha1**
[source, terminal]
----
> npm install bootstrap@5.3.0-alpha1
----

2. Include via links in your HTML file
*Bootstrap requires the usage of an HTML5 doctype, for complete usage of their features.*

[source, html]
----
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
----

You can also download the Bootstrap CSS file and include it into the project. This allows for individual changes in the Bootstrap config.

==== Usage 

Bootstrap is all about preconfigured CSS classes. These can be used to style your HTML elements, regardless of the framework you are using. 

<<<

=== Vuetify

Vuetify is an UI library designed to be used in Vue.js projects. Since it is a newer library, it is not as well known than bootstrap , material UI or tailwind CSS. However, it is a very powerful library that can be used to create beautiful and responsive websites. It is also very easy to use and has a lot of prebuilt components. The bad side about its fresh start into the design industry, is its lack of documentation. Not all functions and components are fully documented, and some of them are even unfinished. However, the company behind vuetify is very active and is constantly working on improving the library.

The library can be installed via npm or yarn. It is a package that needs to be added through one of the following commands.

[source, terminal]
----
> yarn add vuetify@^3.1.11
----

[source, terminal]
----
> npm install vuetify@^3.1.11
----

Vuetify is used such as implementing normal HTML elements, mostly starting with "v-" such as "v-btn" or "v-card". It is also used to implement components such as "v-app-bar" or "v-navigation-drawer".
An example for such a component can be found in the project "Lithoz 3D printing web interface" as quoted below.


[source, html]
----
<template>
    <v-col col="5"
		   :style="`cursor: ${cursorRef}`"
           style="display: flex;justify-content: center;align-items: center;">
        <v-btn :disabled="!buttonGenerallyEnabled || disabled"
               width="100%"
			   @click="isBtnState1 ? sendCommand(primaryCommand) : sendCommand(secondaryCommand)"
               :height="height ?? '17vh'"
               style="white-space: normal;"

               flat>
            <b class="wrapWord" style="width:10vw;text-align:center;overflow-wrap: break-word;" >
				{{
		            buttonText !== undefined ? buttonText :
			            $t(isBtnState1 ? textAssets[primaryCommand] : textAssets[secondaryCommand])
				}}
			</b>
        </v-btn>
    </v-col>
</template>
----

=== Tailwind CSS
[TODO]

=== MUI - Material UI
[TODO]
